log:
  disable_sentry: true
  level: debug

listener:
  addr: :8080

indexer:
  ## rpc or p2p
  mode: rpc

  ## must be either "mainnet", "testnet3" (version 3) , "testnet4" (version 4)  or "regtest3"
  net: regtest

  ## must be empty "" (genesis), or "genesis" (genesis) or other block hash
  initial_block_hash: genesis

  poll_frequency_seconds: 10

rpcNode:
  host: rpcuser_0:rpcpassword_0@bitcoin:18443
  user: rpcuser_0
  pass: rpcpassword_0
  http_post_mode: true
  disable_tls: true
  poll_frequency_seconds: 10

p2pNode:
  host: bitcoin:18444
  agent: indexer
  version: 0.1.0
  network: tcp

db:
  url: postgres://user_0:password_0@db:5432/database_0?sslmode=disable