package data

type UsersQ interface {
	New() UsersQ

	// Insert inserts new user with given credentials into DB
	//
	// user.ID is ignored as it will be autogenerated upon inserting into DB
	// and returned as a result alongside the possible error
	//
	// if user already exists, ErrAlreadyExists is returned
	//
	// if error occured, id=-1 is returned
	Insert(user User) (id int, err error)
	Get(username string) (*User, error)
	Exists(username string) (ok bool, err error)
}

type User struct {
	ID       int    `structs:"id" db:"id"`
	Username string `structs:"username" db:"username"`
	Password []byte `structs:"password" db:"password"`
}
