package data

import "errors"

var ErrAlreadyExists = errors.New("user with provided username already exists")
var ErrUserNotFound = errors.New("user with given username and password does not exist")

type UsersQ interface {
	New() UsersQ

	// Insert inserts new user with given credentials into DB
	//
	// user.ID is ignored as it will be autogenerated upon inserting into DB
	Insert(user User) error
	Get(username string) (*User, error)
	Exists(username string) (ok bool, err error)
}

type User struct {
	ID       int    `structs:"id" db:"id"`
	Username string `structs:"username" db:"username"`
	Password []byte `structs:"password" db:"password"`
}
